version: 2

updates:
  # Keep Go dependencies up to date
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "OctalMesh/development"
    labels:
      - "Dependencies"

  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "OctalMesh/development"
    labels:
      - "Dependencies"
