package commands

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/spf13/cobra"

	"github.com/OctalMesh/Commodore/internal/core/domain"
	"github.com/OctalMesh/Commodore/internal/core/ports"
	"github.com/OctalMesh/Commodore/internal/ui/tui"
)

/*
NewUpCmd returns a ready-to-use `up` command.

brand is the display name shown in the TUI (e.g. "OctalWeb" or "Console").
cfg is the parsed .commodore configuration.
finder locates the working root at runtime.

For a foreman config (role: foreman) the command auto-generates a temporary
Tiltfile that includes each brigadier's dev/Tiltfile plus the optional
user customisation Tiltfile at <root>/dev/Tiltfile.
For a brigadier/worker config it uses <root>/dev/Tiltfile directly.
*/
func NewUpCmd(brand string, cfg domain.Config, finder ports.Finder) *cobra.Command {
	var hud bool

	cmd := &cobra.Command{
		Use:   "up",
		Short: "Start the " + brand + " dev environment with Tilt",
		Long: brand + ` up - start the dev environment.

Launches an interactive TUI: spinner during environment checks, then
streams Tilt output with a live status bar.

Key bindings while running:
  space      open Tilt browser UI
  t          switch to legacy terminal mode (full Tilt TUI)
  ctrl+c     stop Tilt and exit
  ↑/↓ j/k   scroll log  |  g / G  top / bottom  |  pgup/pgdn  page`,
		RunE: func(_ *cobra.Command, _ []string) error {
			root, err := finder.Find()
			if err != nil {
				return err
			}

			tiltfilePath, err := resolveTiltfile(root, cfg)
			if err != nil {
				return err
			}

			argv := []string{"tilt", "up", "--file", tiltfilePath}
			if !hud {
				argv = append(argv, "--hud=false")
			}

			m := tui.NewModel(brand, staticFinder(root), argv)
			p := tea.NewProgram(m)

			final, err := p.Run()
			if err != nil {
				return fmt.Errorf("tui: %w", err)
			}

			finalModel, ok := final.(tui.Model)
			if !ok {
				return fmt.Errorf("unexpected model type: %T", final)
			}

			if finalModel.LegacyMode() {
				legacy := exec.Command("tilt", "up", "--file", tiltfilePath, "--legacy=true")
				if !hud {
					legacy.Args = append(legacy.Args, "--hud=false")
				}
				legacy.Dir = root
				legacy.Stdin = os.Stdin
				legacy.Stdout = os.Stdout
				legacy.Stderr = os.Stderr
				return legacy.Run()
			}

			if ferr := finalModel.FinalErr(); ferr != nil {
				return ferr
			}
			return nil
		},
	}

	cmd.Flags().BoolVar(&hud, "hud", true, "Open Tilt's browser HUD (default: true)")
	return cmd
}

// staticFinder implements ports.Finder and always returns the pre-resolved root.
type staticFinder string

func (s staticFinder) Find() (string, error) { return string(s), nil }

// resolveTiltfile returns the absolute path to the Tiltfile that should be
// passed to `tilt up / tilt down` for the given config.
//
//   - If cfg.Engine.ConfigPath is set it is used as-is (relative to root).
//   - For brigadier / worker configs: <root>/dev/Tiltfile.
//   - For foreman configs: a generated file in the OS temp directory that
//     includes each brigadier's dev/Tiltfile followed by the optional user
//     customisation file at <root>/dev/Tiltfile.
func resolveTiltfile(root string, cfg domain.Config) (string, error) {
	// Explicit override wins.
	if cfg.Engine.ConfigPath != "" {
		if filepath.IsAbs(cfg.Engine.ConfigPath) {
			return cfg.Engine.ConfigPath, nil
		}
		return filepath.Join(root, cfg.Engine.ConfigPath), nil
	}

	if cfg.Role != domain.RoleForeman {
		return filepath.Join(root, "dev", "Tiltfile"), nil
	}

	return generateForemanTiltfile(root, cfg.Brigadiers)
}

// generateForemanTiltfile writes a Tiltfile to the OS temp directory that
// includes each brigadier's dev/Tiltfile (if it exists) and optionally the
// user's customisation file at <root>/dev/Tiltfile.
//
// The generated file is reused across `up` and `down` calls (same path per
// project) and lives in the temp directory - no repo pollution.
func generateForemanTiltfile(repoRoot string, brigadiers []domain.Brigadier) (string, error) {
	name := "commodore-up-" + filepath.Base(repoRoot) + ".tiltfile"
	out := filepath.Join(os.TempDir(), name)

	f, err := os.Create(out)
	if err != nil {
		return "", fmt.Errorf("could not generate foreman Tiltfile: %w", err)
	}
	defer f.Close()

	fmt.Fprintln(f, "# Auto-generated by Commodore - do not edit manually.")
	fmt.Fprintln(f, "# Re-generated on every `ow up` / `ow down` call.")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "version_settings(constraint='>=0.33.0')")
	fmt.Fprintln(f)

	for _, b := range brigadiers {
		tf := filepath.Join(repoRoot, filepath.FromSlash(b.Path), "dev", "Tiltfile")
		if _, err := os.Stat(tf); err == nil {
			fmt.Fprintf(f, "include('%s')\n", filepath.ToSlash(tf))
		}
	}

	// Include user-defined platform-level customisations.
	userTiltfile := filepath.Join(repoRoot, "dev", "Tiltfile")
	if _, err := os.Stat(userTiltfile); err == nil {
		fmt.Fprintln(f)
		fmt.Fprintln(f, "# Platform-level customisations:")
		fmt.Fprintf(f, "include('%s')\n", filepath.ToSlash(userTiltfile))
	}

	return out, nil
}
