package commands

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	tea "github.com/charmbracelet/bubbletea"

	coreruntime "github.com/OctalMesh/Commodore/internal/core/runtime"
	"github.com/OctalMesh/Commodore/internal/ui/tui"
)

// staticFinder implements tui.Finder by always returning a pre-resolved root.
type staticFinder string

func (finder staticFinder) Find() (string, error) { return string(finder), nil }

func runUp(runtimeService *coreruntime.Service, options coreruntime.OperationOptions, hud bool) error {
	tiltfilePaths, rootDirectory, errorValue := runtimeService.CollectTiltfiles(options)
	if errorValue != nil {
		return errorValue
	}

	if len(tiltfilePaths) == 0 {
		// No Tilt-backed nodes: fall back to native per-node execution.
		return runtimeService.Up(options)
	}

	tiltfilePath, errorValue := resolveTiltfilePath(rootDirectory, tiltfilePaths)
	if errorValue != nil {
		return errorValue
	}

	arguments := []string{"tilt", "up", "--file", tiltfilePath}
	if !hud {
		arguments = append(arguments, "--hud=false")
	}

	finalModel, errorValue := runTUI(tui.NewModel(runtimeService.RootNodeID(), staticFinder(rootDirectory), arguments))
	if errorValue != nil {
		return errorValue
	}

	if finalModel.LegacyMode() {
		legacyArguments := []string{"up", "--file", tiltfilePath, "--legacy=true"}
		if !hud {
			legacyArguments = append(legacyArguments, "--hud=false")
		}
		return runLegacyCommand(rootDirectory, "tilt", legacyArguments...)
	}

	return finalModel.FinalErr()
}

func runDown(runtimeService *coreruntime.Service, options coreruntime.OperationOptions) error {
	tiltfilePaths, rootDirectory, errorValue := runtimeService.CollectTiltfiles(options)
	if errorValue != nil {
		return errorValue
	}

	if len(tiltfilePaths) == 0 {
		return runtimeService.Down(options)
	}

	tiltfilePath, errorValue := resolveTiltfilePath(rootDirectory, tiltfilePaths)
	if errorValue != nil {
		return errorValue
	}

	arguments := []string{"tilt", "down", "--file", tiltfilePath}
	finalModel, errorValue := runTUI(tui.NewDownModel(runtimeService.RootNodeID(), staticFinder(rootDirectory), arguments))
	if errorValue != nil {
		return errorValue
	}

	return finalModel.FinalErr()
}

func runTUI(model tui.Model) (tui.Model, error) {
	program := tea.NewProgram(model)
	final, runError := program.Run()
	if runError != nil {
		return tui.Model{}, fmt.Errorf("tui: %w", runError)
	}

	finalModel, ok := final.(tui.Model)
	if !ok {
		return tui.Model{}, fmt.Errorf("unexpected tui model type: %T", final)
	}

	return finalModel, nil
}

func runLegacyCommand(rootDirectory string, command string, arguments ...string) error {
	legacy := exec.Command(command, arguments...)
	legacy.Dir = rootDirectory
	legacy.Stdin = os.Stdin
	legacy.Stdout = os.Stdout
	legacy.Stderr = os.Stderr
	if runError := legacy.Run(); runError != nil {
		return fmt.Errorf("running legacy command %q: %w", command, runError)
	}

	return nil
}

func resolveTiltfilePath(rootDirectory string, tiltfilePaths []string) (string, error) {
	if len(tiltfilePaths) == 1 {
		return tiltfilePaths[0], nil
	}

	return generateCombinedTiltfile(rootDirectory, tiltfilePaths)
}

// generateCombinedTiltfile writes a temp Tiltfile that includes each
// node's Tiltfile via Tilt's include() directive. Re-generated every call.
func generateCombinedTiltfile(rootDirectory string, tiltfilePaths []string) (outputPath string, err error) {
	name := "commodore-fleet-" + filepath.Base(rootDirectory) + ".tiltfile"
	outputPath = filepath.Join(os.TempDir(), name)

	fileHandle, errorValue := os.Create(outputPath)
	if errorValue != nil {
		return "", fmt.Errorf("could not generate fleet Tiltfile: %w", errorValue)
	}
	defer func() {
		if closeError := fileHandle.Close(); closeError != nil && err == nil {
			err = fmt.Errorf("closing generated fleet Tiltfile: %w", closeError)
		}
	}()

	if _, err = fmt.Fprintln(fileHandle, "# Auto-generated by Commodore - do not edit manually."); err != nil {
		return "", fmt.Errorf("writing fleet Tiltfile header: %w", err)
	}
	if _, err = fmt.Fprintln(fileHandle, "# Re-generated on every `commodore up` / `commodore down` call."); err != nil {
		return "", fmt.Errorf("writing fleet Tiltfile header: %w", err)
	}
	if _, err = fmt.Fprintln(fileHandle); err != nil {
		return "", fmt.Errorf("writing fleet Tiltfile spacing: %w", err)
	}
	if _, err = fmt.Fprintln(fileHandle, "version_settings(constraint='>=0.33.0')"); err != nil {
		return "", fmt.Errorf("writing fleet Tiltfile version settings: %w", err)
	}
	if _, err = fmt.Fprintln(fileHandle); err != nil {
		return "", fmt.Errorf("writing fleet Tiltfile spacing: %w", err)
	}
	for _, path := range tiltfilePaths {
		if _, err = fmt.Fprintf(fileHandle, "include('%s')\n", filepath.ToSlash(path)); err != nil {
			return "", fmt.Errorf("writing fleet Tiltfile include: %w", err)
		}
	}

	return outputPath, nil
}
