name: "Lint"

on:
  workflow_dispatch:
  push:
    branches: ["dev", "release"]
  pull_request:
    branches: ["dev", "release"]

permissions:
  contents: read

jobs:
  # Check if the commit message contains skip tags
  check:
    name: "Skip Check"
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.belay.outputs.issued }}

    steps:
      - name: "Setup: Checkout repository"
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 1

      - name: "Run: Check skip tags"
        id: belay
        uses: OctalMesh/belay-action@release
        with:
          signal_tags: "[ci-skip],[lint-skip]"

  # Perform golangci-lint analysis
  lint:
    needs: check
    if: needs.check.outputs.should_skip != 'true'
    name: "GolangCI Lint"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: "Set up Go"
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: "Run golangci-lint"
        run: go tool golangci-lint run ./...
